# Generated by Django 4.1.7 on 2023-04-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0003_remove_ordermodel_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
