# Generated by Django 4.1.7 on 2023-04-14 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0004_ordermodel_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='is_paid',
        ),
    ]
