# Generated by Django 4.1.7 on 2023-04-15 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
