# Generated by Django 4.1.7 on 2023-04-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0007_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_shipped',
            field=models.BooleanField(default=False),
        ),
    ]
