# Generated by Django 4.1.7 on 2023-04-26 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0010_remove_order_ordermodel_order_customer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Orderrs',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='orderrs',
        ),
    ]
