# Generated by Django 4.1.7 on 2023-04-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0011_rename_order_orderrs_rename_order_orderitem_orderrs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='is_shipped',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
