# Generated by Django 4.1.7 on 2023-04-27 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0012_remove_ordermodel_is_shipped_menuitem_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='orderrs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='costumer.orderrs'),
        ),
    ]
