# Generated by Django 4.1.7 on 2023-04-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0013_ordermodel_orderrs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='price',
        ),
    ]
