# Generated by Django 4.1.7 on 2023-05-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0014_remove_ordermodel_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='orderrs',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='orderrs',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderrs',
            old_name='data_orderd',
            new_name='date_ordered',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='name',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ManyToManyField(related_name='items', to='costumer.category'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='orders', to='costumer.menuitem'),
        ),
    ]
